import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/Header";
import ReduxProvider from "@/redux/ReduxProvider";
import CartSyncProvider from "@/components/CartSyncProvider";

import { Pacifico } from "next/font/google";
import WhatsAppButton from "@/components/WhatsAppButton";

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pacifico",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Organic Funda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pacifico.variable}`}>
      <body
        className="font-sans"
      >
        
        <ReduxProvider>
          <CartSyncProvider>
            <AuthProvider>
              {/* <Header/> */}
              {children}
              <WhatsAppButton/>
            </AuthProvider>
          </CartSyncProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
